version: "3.8"
services: 
  frontend:
    build: "./Frontend"  
    container_name: "frontend_service"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080  # Updated to match backend port

  backend:
    build: "./Backend"
    container_name: "backend_service"
    ports:
      - "8080:8000"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:FHn5jtJYmQJGmf1mlaJmR3hAD+LRFhu+QkPj2xsM+Hw= # Replace with your actual key
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=  # Set your MySQL root password
    depends_on:
      - database
    volumes:
      - ./Backend:/var/www/html

  database:
    image: mysql:8.0
    container_name: "mysql_db"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
      - MYSQL_DATABASE=laravel
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: 
